[package]
name = "nexum"
version = "0.1.1"
authors = ["Thiago dos Santos Marcelino <thiagodsmarcelino@gmail.com>"]
edition = "2021"
description = "Library with a collection of commonly used data structures"
license = "MIT"

[dependencies]
